### ISSUE TITLE
Feature request: allow to set a default view period

### ISSUE THREAD

**Issue by terrychenzw** [clairefro/obsidian-plugin-chronos#10]
scanario: 
i create a chronos timeline with many events(for a year period). But i want to set a default view period(specified the start and the end), instead of the whole year period. 

https://github.com/user-attachments/assets/759a05f5-1393-4677-ae81-3e37576e710e

**Comment by clairefro** [comment]
added in v [1.1.2](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.1.2)
