### ISSUE TITLE
Blank line

### ISSUE THREAD

**Issue by JoKo1959** [clairefro/obsidian-plugin-chronos#11]
Thank you for this fantastic plugin. 
I would like to insert blank lines in my timeline. Or is this already possible with the current syntax?

**Comment by clairefro** [comment]
Thanks for the feedback! Tagging for addition in future release

**Comment by clairefro** [comment]
This is now possible in new release [1.0.4](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.4)

````markdown
```chronos
-[2020~] 
- [~2050] 
```
````

![image](https://github.com/user-attachments/assets/656ef9b7-1c09-4b78-b396-eabb16471e1a)

**Comment by JoKo1959** [comment]
Thank you very much! However, I was thinking of a blank line that doesn't show anything, i.e. a vertical space between two events. A horizontal line that can be used to separate events would also be great. This would allow events to be grouped together. Thank you so much.
