### ISSUE TITLE
Use calendarium API as source for dates

### ISSUE THREAD

**Issue by ebullient** [clairefro/obsidian-plugin-chronos#12]
Docs: <https://plugins.javalent.com/calendarium/api>

I use the API to fetch a calendar and regen the contents of two notes statically (and group them by an emoji key that I have), but you could do something similar (without emoji grouping) to grab events from calendarium: 

https://github.com/ebullient/sandbox-customjs/blob/main/src/cmd-timeline.ts

**Comment by clairefro** [comment]
Thanks for sharing your use case! I'd like to assess the demand for Calendar integrations before committing. Chronos is designed more for historical timelines, whereas some great calendar apps already exist

In the meantime, it looks like there is a [Calendarium](https://github.com/javalent/calendarium) plugin for Obsidian already that might suit your needs. You can also use the [Templater](https://github.com/SilentVoid13/Templater) plugin to convert it to Chronos, or the "generate with AI" feature of Chronos

**Comment by ebullient** [comment]
My suggestion was only: folks may already be using calendarium to manage dates (historical or not). You should consider using the API as an alternate source of dates, rather than requiring that folks enter them again in a different/additional format.

**Comment by clairefro** [comment]
curious from a use case perspective - what interests you about rending the Calendarium events in Chronos that Calendarium doesn't already provide for you? For example, are you merging dates from multiple sources?

**Comment by ebullient** [comment]
I know there are some folks that like making timelines for their TTRPG campaign/world-building dates. Some may already have events in Calendarium, but may prefer your visualization to Aprils automatic timelines (<https://github.com/April-Gras/obsidian-auto-timelines>). That plugin scans for calendarium-style span tags, rather than using the API, which would be an option as well.

**Comment by apolo49** [comment]
I second this, this is the exact use case I want to use this plugin for
