### ISSUE TITLE
Ability to choose an alignment for events

### ISSUE THREAD

**Issue by Guillaume-de-Maleprade** [clairefro/obsidian-plugin-chronos#14]
I think it would be great to choose an alignment for event.
The event bubble could be centered, or aligned left/right relative to it's anchor line.
Maybe as a gloabl option and/or local option

**Comment by clairefro** [comment]
Interesting idea! What is the use case you have in mid? Being able to focus quickly on certain events?

**Comment by Guillaume-de-Maleprade** [comment]
I think it would allow to quickly see where the event date is, by not having to find the middle of the event box.
It could also be used to mark a date as the start (if the box is on the right of the line) or the end of an event

**Comment by slartybartfastest** [comment]
I just found your plug-in! Looking really good!

I too wish I could align the event boxes. 

I want the anchor line to define the start and the event box to trail along after. It bugs me that the text of the event starts well before the event happens. If it was a setting, I could change that myself.

**Comment by clairefro** [comment]
Interesting! How do you feel about Points for right alignment? They are available in version 1.0.6 with syntax

`* [Date] title | description`

![image](https://github.com/user-attachments/assets/64116a3f-d8f2-429e-98f2-09f656a39a97)

**Comment by clairefro** [comment]
By the way, you can now choose alignment from the settings. Thanks for the suggestion!

![Image](https://github.com/user-attachments/assets/daa406c2-8556-4048-97c4-ed9c9be0fb09)

**Comment by Guillaume-de-Maleprade** [comment]
Suggestion: 
add a flag *ALIGN* at note level to override global alignment
