### ISSUE TITLE
Add 'point' items

### ISSUE THREAD

**Issue by Guillaume-de-Maleprade** [clairefro/obsidian-plugin-chronos#15]
It would be great to include 'point' items, apparently the only missing type from vis' "'box', 'point', 'range', and 'background'"

This could maybe be added with a star '*' ?

**Comment by clairefro** [comment]
Thank you! I didn't notice this type in the API in the beginning - I agree with the syntax and will add in next release

**Comment by clairefro** [comment]
You can now add points from v [1.0.5](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.5)

Syntax

```
* [Date] Point Name | Description
```

````markdown
```chronos
- [2024-02-26~2024-03-10] Tournament
* [2024-02-26] Game 1 | Austin
* [2024-02-28] Game 2 | Los Angeles
* [2024-03-06] Game 3 | Tokyo
* [2024-03-10] Game 4 | Jakarta
```

![image](https://github.com/user-attachments/assets/b0111ce9-7539-44c6-9f20-9b291a2839c5)

**Comment by clairefro** [comment]
![image](https://github.com/user-attachments/assets/64116a3f-d8f2-429e-98f2-09f656a39a97)
