### ISSUE TITLE
Horizontal Line

### ISSUE THREAD

**Issue by JoKo1959** [clairefro/obsidian-plugin-chronos#17]
The optional insertion of horizontal lines would be nice, hatched or continuous, with a selectable color. This would allow events to be visually separated from each other.

**Comment by clairefro** [comment]
Would [Markers](https://github.com/clairefro/obsidian-plugin-chronos?tab=readme-ov-file#markers-) work?

![image](https://github.com/user-attachments/assets/90b5e19d-e83d-4e09-be33-27bbb9230d28)

**Comment by JoKo1959** [comment]
A horizontal line that spans the entire width of the timeline from left to right would be great

Von: Claire Froelich ***@***.***>
Gesendet: Freitag, 6. Dezember 2024 14:03
An: clairefro/obsidian-plugin-chronos ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [clairefro/obsidian-plugin-chronos] Horizontal Line (Issue #17)


Would Markers<https://github.com/clairefro/obsidian-plugin-chronos?tab=readme-ov-file#markers-> work?

image.png (view on web)<https://github.com/user-attachments/assets/90b5e19d-e83d-4e09-be33-27bbb9230d28>

**Comment by clairefro** [comment]
Ah, I misread :) 

How about [Groups](https://github.com/clairefro/obsidian-plugin-chronos?tab=readme-ov-file#groups-)? 

```
@ [1892-10-08~1941-08-31]{Marina Tsvetaeva} 1892-1941
- [1916] {Marina Tsvetaeva} "Подруга"
- [1928] {Marina Tsvetaeva}  "Поэма концов"
- [1941] {Marina Tsvetaeva} "Записки о поэзии"

@[1899-08-24~1986-06-14]{Jorge Luis Borges} 1899-1986
- [1944] {Jorge Luis Borges} "Ficciones"
- [1949] {Jorge Luis Borges} "El Aleph"
- [1962] {Jorge Luis Borges} "Labyrinths"
```
![image](https://github.com/user-attachments/assets/c696ffb2-cb11-465e-8839-94789e0ce178)

**Comment by clairefro** [comment]
if you prefer unlabeled, you can hack it like this

```
- [2024] { } Item 1
- [2025] {.} Item 2
```

![image](https://github.com/user-attachments/assets/1b840b07-5584-4f0c-8940-ea0e0e599e39)

**Comment by JoKo1959** [comment]
Dear Claire,

thank you, this is a good hack.

Best wishes
Johannes

Von: Claire Froelich ***@***.***>
Gesendet: Freitag, 6. Dezember 2024 15:04
An: clairefro/obsidian-plugin-chronos ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [clairefro/obsidian-plugin-chronos] Horizontal Line (Issue #17)


if you prefer unlabeled, you can hack it like this

- [2024] { } Item 1

- [2025] {.} Item 2

image.png (view on web)<https://github.com/user-attachments/assets/1b840b07-5584-4f0c-8940-ea0e0e599e39>
