### ISSUE TITLE
Points x color issue

### ISSUE THREAD

**Issue by Guillaume-de-Maleprade** [clairefro/obsidian-plugin-chronos#19]
## Points

![image](https://github.com/user-attachments/assets/031b6ffa-da18-42f1-9fc7-60cb2e602216)

## Events

![image](https://github.com/user-attachments/assets/f7258046-03d3-40ae-b72b-d1d1ea9e1653)

## Problem

The text color is not changed when the point has a color.
Maybe the point only should change color ???

**Comment by clairefro** [comment]
Thanks! Fixed in [1.0.7](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.7)

![image](https://github.com/user-attachments/assets/54b4325c-91f6-4907-9dd1-6c5717e442af)

**Comment by KillyMXI** [comment]
I also find implemented solution weird and expected the circle itself to be colored instead.
The only remaining differentiating factor from events is the lack of the drop line.
Points with and without color are more different than points and events with the same color.
