### ISSUE TITLE
[Question] Could this plugin support time in a day?

### ISSUE THREAD

**Issue by Moyf** [clairefro/obsidian-plugin-chronos#2]
Hello! Awesome plugin!
I'm wondering if I can use it to show my day's schedule – so, is there a way to set a "time" for an item?
For example, 3 o'clock today ~ 5 o'clock today?

If so, in what format?
I don't see the use case in the docs, and after trying several scenarios, it doesn't seem to be recognized either.

![image](https://github.com/user-attachments/assets/f8974101-8d47-4474-b57e-c070998851f0)

**Comment by clairefro** [comment]
Thanks for the feedback! 
Yes, you can set hours, even down to the second if you like, using `YYYY-MM-DDThh:mm` syntax. Note that hours use 24-hr military time

For example: 
Today 3~5pm 
`- [2024-11-29T15~2024-11-29T17] Research`

You can designate minutes too 
Today 11am-12:30pm
`- [2024-11-29T11~2024-11-29T12:30] Research`

See more granular examples [here](`- [2024-11-29T15~2024-11-29T17] Research`)


Lastly, you can generate timelines from natural language using "Generate with AI" if you provide an OpenAI API key in the settings. This might be faster 
In an upcoming version I will launch a way to insert items as snippets so there won't be a need to reference documentation

**Comment by Moyf** [comment]
> Thanks for the feedback!
> 
> Yes, you can set hours, even down to the second if you like, using `YYYY-MM-DDThh:mm` syntax. Note that hours use 24-hr military time
> 
> For example: Today 3~5pm `- [2024-11-29T15~2024-11-29T17] Research`
> 
> You can designate minutes too:
> 
> Today 11am-12:30pm `- [2024-11-29T11~2024-11-29T12:30] Research`
> 
> See more granular examples [here](https://github.com/clairefro/obsidian-plugin-chronos?tab=readme-ov-file#a-note-on-dates)
> 
> Lastly, you can generate timelines from natural language using "Generate with AI" if you provide an OpenAI API key in the settings. This might be faster In an upcoming version I will launch a way to insert items as snippets so there won't be a need to reference documentation

WOW Amazing!! Thank you!!
I used to use Mermaid gantt to do the Daily Schedule review, but - it can not interact, and it's kind of hard to read the content.
![image](https://github.com/user-attachments/assets/27915767-7fc2-4773-aea0-46ba9ed0550b)
(I'll record my timestamp with specific format, and use Dataview to collect the information, then generate the gantt and render it)

But now this plugin can totally solve those problems! It saved my day, thank you so much!!

**Comment by Moyf** [comment]
Is there any way to make this timeline *wider* - with more width to show more events?

**Comment by clairefro** [comment]
@moyf, you should be able to zoom out, using mouse or touch-pad scroll down when you hover on a timeline, as shown in the demo below. Th eheight of the timeline will automatically adjust based on the number of items in view.  Let me know if it doesn't work 

![ex-main-demo](https://github.com/user-attachments/assets/9e345bcd-4774-45c5-9d22-fc7839d278fe)


This is interesting feedback, I can consider adding a Zoom control in the timeline for people who are not aware or do not have mousescroll

**Comment by Moyf** [comment]
> @Moyf, you should be able to zoom out, using mouse or touch-pad scroll down when you hover on a timeline, as shown in the demo below. The height of the timeline will automatically adjust based on the number of items in view.
> 
> You can then "refit" all items into view by clicking the "refit" button in lower right. Let me know if it doesn't work for you
> 
> This is interesting feedback, I can consider adding a Zoom control in the timeline for people who are not aware or do not have mouse scroll

Thanks for replying!
Yes, I know that we can use mouse wheel to zoom in&out - Actually that's one of the features that make me love this plugin :P 

But if the event has specific time duration, then the text can be truncated:
![image](https://github.com/user-attachments/assets/0f31dc75-c932-4326-abe4-21a181f2b54a)

The content:
````md
```chronos
- [2024-11-30T12:36~2024-11-30T12:56] A Event with details
- [2024-11-30T15:36~2024-11-30T15:46] That's a long text
- [2024-11-30T13:36] That's a long text
```
````

So I'm thinking if the whole container could be wider, then I can see more events with a higher Zoom state

---

Oh wait a minut, I successed!
![image](https://github.com/user-attachments/assets/a1d5d9d4-4198-458c-8493-6b1f507bd5cd)

```css

/* Chronos Timeline */
.cm-preview-code-block:has(.block-language-chronos),
.cm-preview-code-block .block-language-chronos,
.chronos-timeline-container {
    /* display: none; */
    width: calc(var(--file-line-width) + 20em);
    /* margin-left: -4em !important */
}

.markdown-source-view.mod-cm6 .cm-content .cm-preview-code-block:has(.block-language-chronos) {
    /* display: none; */
    /* width: calc(var(--file-line-width) + 20em); */
    margin-left: -10em !important;
}

```

This trick could be applied to timeline, haha ! Problem solved! 🥳

**Comment by clairefro** [comment]
@Moyf , that is intention behavior for the events with start and end time. Note that you can hover on a truncated element and it will show the full name, or zoom in

**Comment by Vinfall** [comment]
Hi, nice plugin! I know this is closed but it's merely a suggestion (as I found it unsuited for my use case) and this issue is quite relevant.

Is it possible to add "mode" for chronos timeline, typically useful in periodical notes (daily/weekly/monthly journal)? It makes life much easier.

For example, a snippet from daily journal using current syntax:

```javascript
```chronos
- [2024-12-03T08:35~2024-12-03T08:50] Lie-in
- [2024-12-03T08:55] Get-up 🛌
- [2024-12-03T09:10~2024-12-03T09:15] Breakfast 🍞
- [2024-12-03T09:15~2024-12-03T11:20] RSS & Update | gh & xxx
- [2024-12-03T11:30~2024-12-03T12:00] Chronos Timeline
```

Here as everything happens in the same day, the syntax is quite redundant. How about introducing a "mode" for this scenario (concept from syntax highlighter such as [chroma](https://github.com/alecthomas/chroma) in golang or [prism.js](https://github.com/PrismJS/prism), the one used in Obsidian):

```javascript
```chronos {mode=day}
- [2024-12-03T08:35~08:50] Lie-in | Example A
- [08:35~08:50] Lie-in | Example B
- [T08:55] Get-up 🛌 | Do we really need a `T` in day mode?
- [09:10~09:15] Breakfast 🍞 | How about this?
- [09:15~11:20] RSS & Update
- [11:30~12:00] Chronos Timeline
```

By specifying `day` mode, the syntax becomes much simpler and more evident (although I still prefer a vertical timeline). Similarly, `{mode=month}` would be useful in weekly/monthly note by having a more natural expression. I'm not sure if the exact syntax is acceptable for an Obsidian plugin, but it's only a reference and can surely be changed for whatever appropriate.

**Comment by ironc0in** [comment]
I found a better built-in solution in Obsidian:
This makes the graph stretch edge-to-edge.

![Image](https://github.com/user-attachments/assets/458b07f2-c8c2-45a6-9486-bc535dc5cc3e)
