### ISSUE TITLE
Sort items

### ISSUE THREAD

**Issue by Guillaume-de-Maleprade** [clairefro/obsidian-plugin-chronos#20]
![image](https://github.com/user-attachments/assets/d0863d95-8db7-40ef-8283-0596478925fa)

![image](https://github.com/user-attachments/assets/5c007ee0-01cb-4953-a939-8ca5b297b075)

It would be great to sort items by the order they are written in a markdown file.
As of today, items are not ordered by the markdown order.

This could be a settings

see https://visjs.github.io/vis-timeline/examples/timeline/items/itemOrdering.html

**Comment by Guillaume-de-Maleprade** [comment]
I've started to work on this since I'm able to... 
I went for a way to define options with a line like this:

`+ ORDERBY start asc`

I think about doing something like that instead:

`+ ORDERBY start|-content`

Which would order by start date ascending, then content descending, for instance.

Should I continue? :)

**Comment by clairefro** [comment]
@Guillaume-de-Maleprade I'm working on this tonight - not sure if vis-timeline library allows much control over the presentation order. Where were you applying the sorts above?

**Comment by clairefro** [comment]
@Guillaume-de-Maleprade I'm working on this tonight - will make chronological stack order the default and only behavior

**Comment by clairefro** [comment]
@Guillaume-de-Maleprade I played around with this and it seems that the stack order when there are different dates close together on zoom is dependent not on the item order, rather the length of the display text 

https://github.com/user-attachments/assets/90950bac-5d51-4a64-a29b-96b5bf11e31b

If you find a way to do this, feel free to share or contribute. I saw there is an `order` option in vis-timeline docs, but the performance tradeoff doesn't feel worth it 

![image](https://github.com/user-attachments/assets/38cdc796-83c1-42e7-84ba-7d9ba68fb42e)

Appreciate you raising this, but closing for now!
