### ISSUE TITLE
Feature request: Can the subscript of an event graph align it to the beginning

### ISSUE THREAD

**Issue by lzism** [clairefro/obsidian-plugin-chronos#21]
like this <img width="574" alt="image" src="https://github.com/user-attachments/assets/0fe69435-4565-4893-a09a-8934b05ec83a">

**Comment by clairefro** [comment]
for left-aligned items, how do you feel about the new [Points](https://github.com/clairefro/obsidian-plugin-chronos?tab=readme-ov-file#points-) item?

![image](https://github.com/user-attachments/assets/f746581d-bd2a-4071-a314-11606a2ce5b4)

**Comment by lzism** [comment]
I thought about it carefully, time is the most important in the timeline, from the text to the chart of the newly added features should not affect the use of the time sequence of intuition, non-left-aligned is a non-intuitive need to think about the judgment, which is the length of the front and back can not be judged, but also because of the location of the top and bottom can not be judged, which is in the other isssue

point, event, event with duration, and group also seems to be slightly confusing in the presentation, for me it needs charts rather than text, and I still want to make the events independent and comparable, for example, comparing the history of different parts of the world, how each one of them looks like at the same time, and when they start to converge, would it be more appropriate to design a kind of nested presentation, like OB's indented grouping, so I think it might be a good idea. Like OB's indentation grouping, so think about it may be a big project~

**Comment by clairefro** [comment]
@lzism thanks for you thought and feedback. The ability to chose alignment in the settings has been added in [1.0.7](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.7)

Nested subgroups is another beast of a task. Will work on making top level items work well first
