### ISSUE TITLE
Cheetsheet update

### ISSUE THREAD

**Issue by Rick-Kennerly** [clairefro/obsidian-plugin-chronos#29]
I'm getting quite a few parsing fails in the cheetsheet now.  

Also, I have seen reference to a "compact" timeline mode elsewhere, but don't find it referenced in the cheetsheet.

**Comment by clairefro** [comment]
@Rick-Kennerly thanks for raising. Are you using v1.0.8 (latest)? All the cheatsheet blocks are working on my machine ™️ so I'd love to see screenshots of the errors if you still have them!

**Comment by clairefro** [comment]
@Rick-Kennerly also, I'm not familiar with "compact mode" - where did you see this?

**Comment by Rick-Kennerly** [comment]
I'll see.  Probably not.  

Rick H. Kennerly
Virginia Beach, VA
rhkennerly.com
7575895090
***@***.***

Sent with Proton Mail secure email.

**Comment by Rick-Kennerly** [comment]
that's a good question.  You know how it is when you're learning; you read a lot of stuff in many different places.  My feeling is that I was in GitHub suggestions for the plugin.  Maybe I just misremembered.  Or misread.  Or both.  

Anyway, stellar product.  

Rick H. Kennerly
Virginia Beach, VA
rhkennerly.com
7575895090
***@***.***

Sent with Proton Mail secure email.
