### ISSUE TITLE
Linked events open new tab next to active tab

### ISSUE THREAD

**Issue by jordanmills** [clairefro/obsidian-plugin-chronos#38]
If I have multiple tabs open, I have a timeline in one tab, a different tab is active, and I click on an event with a link, instead of the active tab navigating to the link for the event, a new tab is opened adjacent to the active note.  I believe the expected behavior would be to use the active tab, unless opening in a new tab were intended with CTRL+click.  I know the feature is documented as beta, just wanted to add the request.  Thanks!

**Comment by clairefro** [comment]
Thanks for the input! I explicitly coded it to open in a new tab for personal preference, but curious to hear if others feel traditional link behavior (use active tab) is more desirable

**Comment by clairefro** [comment]
Fixe din [1.1.1](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.1.1)

left-click: opens link in current tab
middle-click/ Shift + Click = open link in new tab
