### ISSUE TITLE
Period up to the present time

### ISSUE THREAD

**Issue by Fertion** [clairefro/obsidian-plugin-chronos#5]
Add the ability to specify a time period up to the present time.  
For example, - [2024-02-28T05:30~NOW].

**Comment by clairefro** [comment]
Thanks for the suggestion! I've added this in version [1.0.2](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.2) which is now available

You can omit the date in a range for it to default to "now". Note that "now" will be the time of render. 

````markdown
```chronos
- [ 1980~] This event is 1980 until now
```
````

![image](https://github.com/user-attachments/assets/d9d523cd-4b38-44a1-ba12-9c60038c77a2)


While it works for ranges from the past or into the future, I recommend only using it with past dates. Ranges into the future will break once "now" is later than the end date.

**Comment by clairefro** [comment]
@Fertion doh - thank you. I've updated the manifests for all releases. latest version available should be `1.0.3` now
