### ISSUE TITLE
Feature request: parse chronos codeblocks from all (or selection of) notes into one interactive timeline

### ISSUE THREAD

**Issue by koenbunders** [clairefro/obsidian-plugin-chronos#6]
I have many atomic notes. I'd like to add a chronos codeblock in some of them. 
My request: a feature that parses all chronos codeblock from all notes in the vault into one interactive timeline.

A second iteration would hopefully be able to deal with parsing all chronos codeblocks from _a selection_ of notes in the vault into one interactive timeline. The selection should i.m.h.o be based on a value in YAML properties.

**Comment by Guillaume-de-Maleprade** [comment]
You can most certainly achieve this with dataview for the time being.

**Comment by koenbunders** [comment]
> You can most certainly achieve this with dataview for the time being.

Could you provide an example of how to do it?

**Comment by clairefro** [comment]
@koenbunders I got this to work with the Templater plugin
1. Install Templater 
2. Create a note with the below script, replacing `your/folder/path` with the path to the folder you want to merge chronos blocks. The template note should live outside your target directory 
```
<%*
const folderPath = 'your/folder/path'; // Folder where your chronos files are located
let combinedContent = '```chronos\n'; // Initialize combined content with opening fence

// Get all files in the vault
const files = app.vault.getFiles();

// Loop through files and check for chronos code blocks
for (const file of files) {
    if (file.path.startsWith(folderPath)) {
        // Read the file content asynchronously
        const content = await app.vault.read(file);
        
        // Regex to match 'chronos' code blocks
        const regex = /```chronos([\s\S]*?)```/g;
        let match;
        
        // Check if there are any matches in the file
        while ((match = regex.exec(content)) !== null) {
            // Append content from the matched block (excluding the code block delimiters)
            combinedContent += match[1] + '\n';
        }
    }
}

combinedContent += '```'; // Close the final code block

// Output the combined content to the note
tR += combinedContent;
%>
```

3. Open command palette (Ctrl + P), type "Templater" and run "Create new note from template"
