### ISSUE TITLE
[Bug] Incorrect date in pop-up message

### ISSUE THREAD

**Issue by Fertion** [clairefro/obsidian-plugin-chronos#8]
Hi, the date in the popup message is shifted 1 day for some reason.

```chronos
- [2023-11-07] #pink test
```

![image](https://github.com/user-attachments/assets/c03ca1bb-b2b0-4ec7-9b1e-5eb0b50e8850)

**Comment by Fertion** [comment]
If you use this variant, yesterday's date is displayed instead of today's date
```chronos
- [2023-11-07~] #pink test
```
![image](https://github.com/user-attachments/assets/6e6ba8ed-764e-430c-9696-3fe8976d5382)

**Comment by clairefro** [comment]
Thank you! Interesting - it's working for me

![image](https://github.com/user-attachments/assets/9725d602-ad7b-4652-bd70-d4c24b2bfe43)

I'm wondering if this is a UTC time issue that isn't addressed in the code. What time zone is your system in?

**Comment by Fertion** [comment]
> What time zone is your system in?

UTC+3:00

**Comment by Fertion** [comment]
> I'm wondering if this is a UTC time issue that isn't addressed in the code

Yes, if you switch to UTC+5:00, everything works correctly. At the time of writing this comment, both UTC-5:00 and UTC+3:00 fall on the same date, December 1, 2024.

**Comment by clairefro** [comment]
Thank you - I spent many hours trying to address this before release but looks like I must have missed a case! 

I will work on fixing this

**Comment by clairefro** [comment]
I think this is resolved in new version `1.0.3`, [forcing UTC time](https://github.com/clairefro/obsidian-plugin-chronos/commit/226eec6ec689fdfa54bf453de749c72922219dda) in date display

If you still have problems let me know!

**Comment by Fertion** [comment]
> If you still have problems let me know!

Updated to 1.0.3, rebooted obsidian completely, but the problem persisted in the 
UTC+3:00.
![image](https://github.com/user-attachments/assets/41f5cc87-eebf-41c5-9ac8-9d80cc31daca)

**Comment by clairefro** [comment]
Appreciate your patience on this and detailed bug report. Should be resolved in [1.0.4](https://github.com/clairefro/obsidian-plugin-chronos/releases/tag/1.0.4)

**Comment by Fertion** [comment]
Confirmed, everything is correct now, thank you!
