### ISSUE TITLE
[Bug] When zooming out, non-overlapping events are moved to different lines

### ISSUE THREAD

**Issue by Fertion** [clairefro/obsidian-plugin-chronos#9]
At different scales, events can appear on one line or several. But given that they don't overlap, it would be great if they stayed on one line.

```chronos
- [2024-03-23~2024-04-13] text
- [2024-04-14~2024-05-25] text2
```

![image](https://github.com/user-attachments/assets/1d959aa8-a688-424d-8d65-9eb8fbccc087)
![image](https://github.com/user-attachments/assets/2596eb4c-044e-4c0e-968d-895cbd2ab137)

**Comment by clairefro** [comment]
Thanks for the report. This is native behavior of the underlying `vis-timeline` library and I cannot address
